site_name: AWS IoT Core
site_url: https://github.com/yilmaznaslan/aws-iot-core-create-many-things-boto3
site_description: Project documentation with Markdown.
site_author: MkDocs Team

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: ""
site_dir : 'docs'
docs_dir : 'markdown'
theme:
    name: readthedocs
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true


nav:
    - Introduction: index.md
    - User Guide: user_guide.md
    - Developer Guide:  
        - Connecting to AWS IoT Core: developer_guide.md
        - Security: security.md
        - Rules: rules.md
        - Device provisioning: device_provisioning.md
